// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

// Product defines model for Product.
type Product struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	ImageUrl    string `json:"imageUrl"`
	Name        string `json:"name"`
	Price       int64  `json:"price"`
}

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	// Ids Comma-separated product IDs to filter by.
	Ids *[]string `form:"ids,omitempty" json:"ids,omitempty"`
}
